# Generated by Django 2.1.1 on 2018-12-30 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='qa.InputType'),
        ),
    ]
