# Generated by Django 2.1.1 on 2018-12-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20181230_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='QuestionCategories',
        ),
    ]
